## 01. Numpy

- 다차원 배열을 쉽고 효율적으로 사용할 수 있도록 지원하는 파이썬 라이브러리
- 데이터 분석 라이브러리에 많이 사용됨


### 1-1. ndarray
- numpy의 핵심 데이터 구조
- 동일한 자료형의 다차원 배열

In [51]:
import numpy as np

In [ ]:
# ndarray의 생성
a = np.array([[1,2,3], [4,5,6]])            # 2차원
b = np.array([1.0, 3.14, 1.24])             # 1차원

a

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
# 배열의 구조
print(f"배열의 구조: {a.shape}")

# 배열의 차원수
print(f"배열의 차원: {a.ndim}")

# 데이터 타입
print(f"배열의 데이터 타입: {a.dtype}")
print(f"배열의 데이터 타입: {b.dtype}")

# 형 변환
new_a = a.astype(np.float64)
print(f"수정한 배열의 데이터 타입: {new_a.dtype}")


배열의 구조: (2, 3)
배열의 차원: 2
배열의 데이터 타입: int64
배열의 데이터 타입: float64
수정한 배열의 데이터 타입: float64


In [13]:
# 3차원 행렬
a = np.array([[[1,2,3], [4,5,6]], 
              [[1,2,3], [4,5,6]],
              [[1,2,3], [4,5,6]]])

print(f"배열의 구조: {a.shape}")
print(f"배열의 차원: {a.ndim}")

배열의 구조: (3, 2, 3)
배열의 차원: 3


In [14]:
# 4차원 행렬
a = np.array([[[[1,2,3], [4,5,6]], 
              [[1,2,3], [4,5,6]],
              [[1,2,3], [4,5,6]]],
              
              [[[1,2,3], [4,5,6]], 
              [[1,2,3], [4,5,6]],
              [[1,2,3], [4,5,6]]]])

print(f"배열의 구조: {a.shape}")
print(f"배열의 차원: {a.ndim}")

배열의 구조: (2, 3, 2, 3)
배열의 차원: 4


### 1-2. 배열 초기화

In [8]:
import numpy as np
# 모든 요소가 0인 배열 생성
print(np.zeros((3,4)))                              # 2차원
print(np.zeros((2,3,4), dtype=np.int64))            # 3차원     # int64 -> 소수점 사라짐

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [23]:
# 모든 요소가 1인 배열 생성
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [28]:
# (원소의 값이) 초기화 되지 않은 배열 생성
np.empty((2,3))

array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
# 주어진 값으로 채운 배열
np.full((3, 3), 7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [11]:
# 단위 행렬
print(np.eye(3, 3))
print(np.eye(3, 5, -1))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]


### 1-3. 범위 기반 배열 생성

In [12]:
# arrange: range() 와 유사한 기능 제공
# 시작 이상 끝 미만의 정수 배열을 지정한 간격으로 생성
print(np.arange(0, 10))
print(np.arange(0, 10, 2))

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [13]:
# linspace : 시작 ~ 끝까지 균일 간격으로 지정한 개수만큼 숫자를 생성
# 끝을 포함

print(np.linspace(10, 100, 10))
print(np.linspace(0.1, 1, 10))

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


### 1-4. 랜덤 배열 생성

In [ ]:
# random.rand(m,n) : 0 ~ 1 사이의 난수로 초기화

np.random.rand(2,3)


array([[0.72860802, 0.42494477, 0.2342449 ],
       [0.58545945, 0.27420743, 0.51793467]])

In [49]:
# random.randn(m,n) : 표준 정규분포를 따르는 난수로 초기화
# 표준 정규분포 : 평균 0, 분산 1인 정규분포

np.random.randn(2,4,5)

array([[[ 0.35012773,  0.09141364, -1.76829382,  0.11623813,
         -0.4121351 ],
        [-1.56499425,  0.03579492,  0.74503456,  0.96163637,
         -0.56530278],
        [ 1.43813726, -2.508991  ,  1.83605737,  1.12809374,
         -0.33767653],
        [-1.48900202, -0.41411166,  0.3483623 , -2.25438656,
          1.54739915]],

       [[ 2.25710005,  0.49329907, -0.07981603, -0.42820949,
         -0.79471819],
        [-0.17920129, -0.57543341,  0.48808518, -1.98676298,
         -0.72822409],
        [ 0.35164259,  1.97614605,  0.0625254 ,  1.2196352 ,
          0.12460916],
        [-0.39853295, -2.89213765,  0.37470003,  1.24822103,
         -0.40180127]]])

In [ ]:
# random.randint(low, high, size)

np.random.randint(10, 20, (2,4))            # 10 ~ 20 사이 정수(2 x 4) 배열

array([[15, 17, 17, 17],
       [11, 13, 15, 18]], dtype=int32)

In [ ]:
# random.seed() : 난수 생성시 시작값을 제공함           

np.random.seed(42)
np.random.randn(2,3)                        # 결과값 고정

array([[ 0.49671415, -0.1382643 ,  0.64768854],
       [ 1.52302986, -0.23415337, -0.23413696]])

In [68]:
# RNG(Random Number Generator) : 최근 Numpy 사용에서 권장되는 방식
from numpy.random import default_rng

rng = default_rng(seed=42)
rng2 = default_rng(seed=10)

print(rng.random((3,2)))
print(rng2.random((3,2)))


[[0.77395605 0.43887844]
 [0.85859792 0.69736803]
 [0.09417735 0.97562235]]
[[0.95600171 0.20768181]
 [0.82844489 0.14928212]
 [0.51280462 0.1359196 ]]


In [ ]:
# <실습1-1> 0으로 채워진 크기 (3, 4) 배열을 생성한 후, 모든 값을 5로 채우는 새로운 배열을 만드세요.
a1 = np.zeros([3,4])
a1_2 = np.full((3,4),5)
print(a1, a1_2, a1+a1_2, sep="\n")

# <실습1-2> 0부터 20까지 2씩 증가하는 1차원 배열을 생성하세요.
a2 = np.arange(0,21,2)
b2 = np.linspace(0,20, 11)
print(a2)
print(b2)

# <실습1-3> 0~1 사이의 실수 난수를 가지는 (2, 3) 크기의 배열을 생성하세요.
a3 = np.random.rand(2,3)
print(a3)

# <실습1-4> 평균이 100, 표준편차가 20인 정규분포 난수 6개를 생성하세요.
a4 = np.random.normal(100, 20, 6)
print(a4)

# <실습1-5> 1부터 20까지의 정수를 포함하는 1차원 배열을 만들고, 이 배열을 (4, 5) 크기의 2차원 배열로 변환하세요.
a5 = np.arange(1,21)
a5.shape = (4,5)
print(a5)

# a5 = np.arange(1,21).reshape(4,5)
# print(a5)

# <실습1-6> 0부터 1까지 균등 간격으로 나눈 12개의 값을 가지는 배열을 생성하고, 이를 (3, 4) 크기로 변환하세요.
a6 = np.linspace(0,1,12)
a6.shape = (3,4)
print(a6)

# a6 = np.linspace(0,1,12).reshape(3,4)
# print(a6)

# <실습1-7> 0~99 사이의 난수로 이루어진 (10, 10) 배열을 생성한 뒤, np.eye()로 만든 단위 행렬을 더하여 대각선 요소가 1씩 증가된 배열을 만드세요.

a7 = np.random.randint(0,100,(10,10))
a7_eye = np.eye(10)
a7_added = a7 + a7_eye
print(a7_added)

# <실습1-8> 0~9 사이의 난수로 이루어진 (2, 3, 4) 3차원 배열을 생성하세요
a8 = np.random.randint(0,10,(2,3,4)) 
print(a8)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]
[ 0  2  4  6  8 10 12 14 16 18 20]
[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]
[[0.64996393 0.70196688 0.79579267]
 [0.89000534 0.33799516 0.37558295]]
[103.30045596  82.88142164  99.20727716  89.30674516  64.2300699
 107.14609084]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[0.         0.09090909 0.18181818 0.27272727]
 [0.36363636 0.45454545 0.54545455 0.63636364]
 [0.72727273 0.81818182 0.90909091 1.        ]]
[[ 58.  57.  85.  48.  51.  41.  69.  14.  53.  59.]
 [ 96.   8.  52.  59.   4.  67.   5.  95.  93.  46.]
 [ 98.  54.  40.  51.  15.  12.  29.  18.  16.  62.]
 [ 18.  91.  57.  55.  89.  89.  61.  22.   8.  11.]
 [  0.  57.   0.  33.  96.  47.  88.   0.  15.  60.]
 [ 63.  62.  68.  21.  92.  67.  75.  25.  15.  50.]
 [ 85.  56.  28.  77.  91.  68.  47.  93.  61.  68.]
 [ 75.  15.  89.  89.  47.  84.  38. 100.  32.  93.]
 

### 1-5. 인덱싱과 슬라이싱
- 다차원 배열을 다루는 편의 기능 제공
- Python의 시퀀스보다 빠름

In [124]:
# 인덱싱
a = np.array([10,20,30,40,50])
print(a[2])
print(a[-1])

30
50


In [130]:
# 다차원 인덱싱
# 파이썬 리스트
matrix = [[1,2,4], [4,5,6]]
print("파이썬 인덱싱: ", matrix[1][1])

# numpy 배열
a2 = np.array([[1,2,4], [4,5,6]])
print("numpy 인덱싱: ", a2[1,1])

# 3차원 배열 인덱싱
a3 = np.arange(24).reshape(2,3,4)
print(a3)
print("3차원 인덱싱: ", a3[1,1,1])


파이썬 인덱싱:  5
numpy 인덱싱:  5
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
3차원 인덱싱:  17


In [131]:
# 슬라이싱
# arr[행_슬라이스, 열_슬라이스]
# arr[..., 4차원 슬라이스, 3차원 슬라이스, 2차원, 1차원]

a1 = np.array([10,20,30,40,50])
print(a1[1:3])
print(a1[2:])
print(a1[:2])
print(a1[:])
print(a1[::2])
print(a1[::-1])

[20 30]
[30 40 50]
[10 20]
[10 20 30 40 50]
[10 30 50]
[50 40 30 20 10]


In [135]:
# 파이썬 리스트와의 차이
# 파이썬 리스트
py_list = [10,20,30,40,50]
sliced = py_list[1:4]
sliced[1] = 100
print("py원본: ", py_list)
print("py슬라이싱: ", sliced)

# Numpy 배열
a1 = np.array([10,20,30,40,50])
a1_sliced = a1[1:4]
a1_sliced[1] = 100
print("Numpy원본: ", a1)
print("Numpy슬라이싱: ", a1_sliced)


py원본:  [10, 20, 30, 40, 50]
py슬라이싱:  [20, 100, 40]
Numpy원본:  [ 10  20 100  40  50]
Numpy슬라이싱:  [ 20 100  40]


In [74]:
#<실습2>
# 2-1. 다음 배열에서 2, 4, 6번째 요소를 Fancy Indexing으로 선택하세요.
arr1 = np.arange(10, 30, 2)
print("문제1: ", arr1[[1,3,5]])

# 2-2. 3x3 배열에서 왼쪽 위 → 오른쪽 아래 대각선의 요소만 인덱싱으로 추출하세요.
arr2 = np.arange(1, 10).reshape(3, 3)
arr2_arr2 = arr2[[0,1,2],[0,1,2]]
print("문제2: ", arr2_arr2)

# 2-3. 3x4 배열에서 마지막 열만 선택해 모두 -1로 변경하세요.
arr3 = np.arange(1, 13).reshape(3, 4)
arr3[:,-1] = -1 
print("문제3: ", arr3)

# 2-4. 4x 4 배열에서 행을 역순, 열을 역순으로 각각 슬라이싱해 출력하세요.
arr4 = np.arange(1, 17).reshape(4, 4)
arr4_1 = arr4[::-1]
arr4_2 = arr4[:,::-1]

print("문제4-1: ", arr4_1)
print("문제4-2: ", arr4_2)

문제1:  [12 16 20]
문제2:  [1 5 9]
문제3:  [[ 1  2  3 -1]
 [ 5  6  7 -1]
 [ 9 10 11 -1]]
문제4-1:  [[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
문제4-2:  [[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


In [ ]:
# 2차원 배열 슬라이싱

a2 = np.arange(1,21).reshape(4,5)
print(a2)

# # 행 슬라이싱
print(a2[0])                                    # [1 2 3 4 5]
print(a2[1])                                    # [ 6  7  8  9 10]
print(a2[1:3])                                  # [[ 6  7  8  9 10] /  [11 12 13 14 15]]
print(a2[2:])                                   # [[11 12 13 14 15] /  [16 17 18 19 20]]

# 열 슬라이싱
print(a2[:,2])                                  # [ 3  8 13 18]
print(a2[:, -1])                                # [ 5 10 15 20]
print(a2[:, 1:3])                               # [[ 2  3] / [ 7  8] / [12 13] / [17 18]]

# 행과 열 슬라이싱
print(a2[1:3, 2:4])                             # [[ 8  9] / [13 14]]
print(a2[2: , 3:])                              # [[14 15] /  [19 20]]
print(a2[::2, ::2])                             # [[ 1  3  5] /  [11 13 15]]


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[ 3  8 13 18]
[ 5 10 15 20]
[[ 2  3]
 [ 7  8]
 [12 13]
 [17 18]]


In [ ]:
# 3차원 슬라이싱
a3 = np.arange(36).reshape(3, 3, 4)
print(a3)
print(a3[1,1,1:3])          # [17 18]


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]
[17 18]


In [ ]:
# 얕은 복사 : 복사본이 원본이랑 메모리를 공유 -> 변경사항이 서로에게 영향을 줌

a1 = np.array([1,2,3])
a1_viewd = a1.view()
a1_viewd[1] = 10
print("원본", a1)                               # 원본 [ 1 10  3]
print("복사본", a1_viewd)                       # 복사본 [ 1 10  3]

# 깊은 복사 : 복사본이 원본과 독립적으로 복사됨 -> 서로 영향을 주지 X
a2 = np.array([1,2,3])
a2_copied = a2.copy()
a2_copied[1] = 10
print("원본", a2)                               # 원본 [1 2 3]
print("복사본", a2_copied)                      # 복사본 [ 1 10  3]


원본 [ 1 10  3]
복사본 [ 1 10  3]
원본 [1 2 3]
복사본 [ 1 10  3]


In [ ]:
# Fancy Indexing
# 정수 배열을 사용하여 여러 인덱스로 여러 요소를 한번에 선택
af = np.arange(1,21)
print(af)
print(af[[4,7,11]])                                 # [ 5  8 12]

af2 = np.arange(1,21).reshape(4,5)
print(af2)
print(af2[[1,3],[2,4]])                             # [ 8 20]

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 5  8 12]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[ 8 20]


In [ ]:
# Boolean Indexing
ab = np.linspace(10, 100, 10)
print(ab)
print(ab[ab>40])                    # [ 50.  60.  70.  80.  90. 100.]


# Boolean masking
ab2 = np.arange(0,21)
print(ab2)
mask = ab2 % 2 == 0
print(mask)                         # [ True False  True False  True False  True False  True False  True False
                                    #  True False  True False  True False  True False  True]
print(ab2[mask])                    # [ 0  2  4  6  8 10 12 14 16 18 20]

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
[ 50.  60.  70.  80.  90. 100.]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ True False  True False  True False  True False  True False  True False
  True False  True False  True False  True False  True]
[ 0  2  4  6  8 10 12 14 16 18 20]


In [72]:
# <실습>
# 2-5. 4x 5 배열에서 가운데 2x 3 부분을 슬라이싱한 뒤 copy()를 이용해 독립 배열을 만드세요.
arr5 = np.arange(1, 21).reshape(4, 5)
arr5_copied = arr5[1:3, 1:4].copy()
print("문제2-5: ", arr5_copied)

# 2-6. 3x 4 배열에서 짝수이면서 10 이상인 값만 선택하세요.(&을활용)
arr6 = np.array([[4 , 9, 12, 7], [10, 15, 18, 3], [2 , 14, 6, 20]])
arr6_arr6 = arr6[(arr6 % 2 == 0) & (arr6 >= 10)]
print("문제2-6: ", arr6_arr6)

# 2-7. 5x 5 배열에서 2, 4번째 행을 선택하고, 선택된 행에서 열 순서를 [4, 0, 2]로 재배치하세요.
arr7 = np.arange(1, 26).reshape(5, 5)
arr7_r = arr7[[1,3]]
arr7_c = arr7_r[:,[4,0,2]]
print("문제2-7:", arr7_c)


문제2-5:  [[ 7  8  9]
 [12 13 14]]
문제2-6:  [12 10 18 14 20]
문제2-7: [[10  6  8]
 [20 16 18]]


In [73]:

# 2-8. 5x 3 배열에서 각 행의 첫 번째 값이 50 이상인 행만 Boolean Indexing으로 선택하세요.
arr8 = np.array([[10, 20, 30], [55, 65, 75], [40, 45, 50], [70, 80, 90], [15, 25, 35]])
print("문제8: ", arr8[arr8[:, 0] >= 50])

# 2-9. 4x 4 배열에서 (0,1), (1,3), (2,0), (3,2) 위치의 요소를 한 번에 선택하세요.
arr9 = np.arange(1, 17).reshape(4, 4)
arr9_arr9 = arr9[[0,1,2,3],[1,3,0,2]]
print("문제9: ", arr9_arr9)

# 2-10. 3차원 배열 (2, 3, 4)에서 모든 블록에서 두 번째 열만 추출해 새로운 2차원 배열 (2, 3)을 만드세요.
arr3d = np.arange(24).reshape(2, 3, 4)
arr10 = arr3d[:, :, 1]
print("문제10:", arr10)

문제8:  [[55 65 75]
 [70 80 90]]
문제9:  [ 2  8  9 15]
문제10: [[ 1  5  9]
 [13 17 21]]


In [146]:
# <문제3-1>
arr = np.arange(25).reshape(5,5)
print("가운데 행:", arr[2])
print("가운데 열: ", arr[:,2])


가운데 행: [10 11 12 13 14]
가운데 열:  [ 2  7 12 17 22]


In [ ]:
# <문제3-2>
arr = np.random.randint(0,100,(10,10))
result = arr[::2]
print(result)

[[ 7 14 30 58 56 54 88 53 82 68]
 [86 66 96 49 84 39 33  1 58  7]
 [75 69 69 41 33 44 67 36 68  0]
 [62  3 41 90 96 36  6 43 79 98]
 [88 53 70 36 43 38 79 16 21 77]]


In [ ]:
# <문제3-3>
arr = np.arange(0,50).reshape(5,10)
print(arr[1:4,2:7])

[[12 13 14 15 16]
 [22 23 24 25 26]
 [32 33 34 35 36]]


In [178]:
# <문제3-4>
# arr = np.random.randint(0,10,(4,4))

# main = [arr[i,i] for i in range(4)]
# anti = [arr[i,3-i] for i in range(4)]

# print(main)
# print(anti)
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# print(arr[[0,1,2,3],[0,1,2,3]])
# print(arr[[0,1,2,3],[3,2,1,0]])
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
arr = np.random.randint(0,10,(4,4))
print(arr)
answer = []
answer2 = []
for i in range(4):
    answer.append(arr[i][i])
    answer2.append(arr[i][3-i])
print("주대각선: ", answer)
print("부대각선: ", answer2)


[[0 6 7 1]
 [3 7 2 7]
 [7 0 0 0]
 [3 6 8 1]]
주대각선:  [np.int32(0), np.int32(7), np.int32(0), np.int32(1)]
부대각선:  [np.int32(1), np.int32(2), np.int32(0), np.int32(3)]


In [183]:
# <문제3-5>
arr = np.random.randint(0,10,(3,4,5))
print(arr)
print(arr[1,0,-1])

[[[5 2 7 2 8]
  [9 8 0 3 5]
  [0 4 8 3 0]
  [7 4 3 6 4]]

 [[8 4 7 8 7]
  [6 1 8 0 0]
  [1 4 4 0 0]
  [2 4 5 0 9]]

 [[8 3 7 8 8]
  [6 9 2 8 2]
  [9 5 8 3 7]
  [0 4 7 2 0]]]
7


In [ ]:
# <문제3-6,7,8>
arr = np.arange(35,75).reshape(10,4)
print("문제6:\n", arr)
print("문제7:\n", arr[::-1])
print("문제8:\n", arr[1:9, 2:4])            # arr[1:-1,2:]

문제6:
 [[35 36 37 38]
 [39 40 41 42]
 [43 44 45 46]
 [47 48 49 50]
 [51 52 53 54]
 [55 56 57 58]
 [59 60 61 62]
 [63 64 65 66]
 [67 68 69 70]
 [71 72 73 74]]
문제7:
 [[71 72 73 74]
 [67 68 69 70]
 [63 64 65 66]
 [59 60 61 62]
 [55 56 57 58]
 [51 52 53 54]
 [47 48 49 50]
 [43 44 45 46]
 [39 40 41 42]
 [35 36 37 38]]
문제8:
 [[41 42]
 [45 46]
 [49 50]
 [53 54]
 [57 58]
 [61 62]
 [65 66]
 [69 70]]


In [ ]:
# <문제3-9>
arr = np.random.randint(1,51,(5,6))
print(arr[arr % 2 == 0])

#~~~~~~~~~~~~~~~~~~~~~~~~~~
mask = arr % 2 == 0
print(mask)
a9 = arr[mask]
print(a9)

[20 22 24 10 36 18 30 34 12 14 26 32 50 18 20  4 22]


In [ ]:
# <문제3-10>
arr = np.arange(0,100).reshape(10,10)
print(arr[[1,3,5]][:,[2,4,6]])


[[12 14 16]
 [32 34 36]
 [52 54 56]]


In [188]:
# <문제 11>
arr = np.random.randint(0,10,15)
arr1 = arr[arr % 2 == 0]
arr2 = arr1[arr1 >= 5] 
print(arr1)
print(arr2)

[2 8 8 6 2 4 6 0 8 0 2]
[8 8 6 6 8]
