## 02. NumPy

### 2-1. NumPy 배열 연산


In [6]:
import numpy as np

In [ ]:
# 배열 간 연산(1차원)
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

print(a1 + a2)                  # [5 7 9]
print(a1 - a2)                  # [-3 -3 -3 ]

[5 7 9]
[-3 -3 -3]


In [ ]:
# 배열 간 연산(2차원)
a1 = np.arange(1,5).reshape(2,2)
a2 = np.arange(11,15).reshape(2,2)

print(a1)                       # [1 2] / [3 4]]
print(a2)                       # [[11 12] / [13 14]]
print(a1 + a2)                  # [[12 14] / [16 18]]
print(a2 - a1)                  # [[10 10] / [10 10]]

[[1 2]
 [3 4]]
[[11 12]
 [13 14]]
[[12 14]
 [16 18]]
[[10 10]
 [10 10]]


In [ ]:
# 배열과 스칼라 연산 (1차원)
a1 = np.array([1,2,3,4])
print(a1 + 10)              # [11 12 13 14]
print(a1 * 2)               # [2 4 6 8]


[11 12 13 14]
[2 4 6 8]


In [ ]:
# 배열과 스칼라 연산 (2차원)
a1 = np.arange(1,5).reshape(2,2)
a2 = np.arange(11,15).reshape(2,2)

print(a1)                    # [[1 2] / [3 4]]
print(a2)                    # [[11 12] /  [13 14]]
print(a1 + 5)                # [[6 7] / [8 9]]
print(a2 * 3)                # [[33 36] / [39 42]]
print(a2 / 2)                # [[5.5 6. ] / [6.5 7. ]]

[[1 2]
 [3 4]]
[[11 12]
 [13 14]]
[[6 7]
 [8 9]]
[[33 36]
 [39 42]]
[[5.5 6. ]
 [6.5 7. ]]


In [ ]:
# 배열의 구조가 다를 경우
a1 = np.array([1,2])
a2 = np.array([1,2,3])

print(a1 + a2)                  # ValueError


ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [ ]:
# 브로드캐스팅
# 자동으로 배열의 크기를 확장 -> 서로 다른 크기의 배열 간 연산을 가능하게 하는 기능
# 1. 두 배열의 차원을 뒤(낮은 차원)에서부터 비교
# 2. 크기가 같거나
# 3. 한쪽이 1인 경우 확장이 가능

a1 = np.array([[1, 2, 3], 
               [4, 5, 6]])          # (2,3)
a2 = np.array([10, 20, 30])         # 길이가 3인 1차원 배열 (3,)

# 1차원 길이 3
[10, 20, 30]

# 2차원으로 변형 (1,3)
[[10, 20, 30]]

# 2차원의 행이 2 - > 2로 확장
[[10, 20, 30],
 [10, 20, 30]]

print(a1 + a2)                      # [[11 22 33] / [14 25 36]]

[[11 22 33]
 [14 25 36]]


In [ ]:
# 브로드캐스팅 예제
a1 = np.array([[1], [2], [3]])      # (3,1)
a2 = np.array([10, 20, 30])         # (3,)

# a2 : (3,) - > (1,3) 변형
[[10, 20, 30]]

# a1과 a2 비교 - > a1(3,1) a2(1,3)
[[1, 1, 1], [2 ,2 ,2], [3, 3, 3]]
[[10, 20, 30], [10, 20, 30], [10, 20, 30]]

print(a1 + a2)                      # [[11 21 31] / [12 22 32] / [13 23 33]]

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [ ]:
# <실습1>
# 1. 다음 배열을 생성하고, 모든 요소에 3을 더하세요.
arr = np.array([1,2,3,4])
print(arr + 3)


[4 5 6 7]


In [8]:
# 2. 아래 2차원 배열에서 각 요소를 -1로 곱한 새로운 배열을 만드세요.
arr = np.array([[5, 10],
                [15, 20]])
print(arr * -1)


[[ -5 -10]
 [-15 -20]]


In [10]:
# 3. 아래 두 배열의 요소별 곱셈과 나눗셈 결과를 각각 출력하세요.
arr1 = np.array([2, 4, 6])
arr2 = np.array([1, 2, 3])

print(arr1 * arr2)
print(arr1 / arr2)

[ 2  8 18]
[2. 2. 2.]


In [19]:
# 4. 아래 배열에서 모든 요소를 최대값 100으로 만들기 위해 필요한 값을 더한 결과 배열을 브로드 캐스팅으로 만드세요.
arr = np.array([[95, 97],
                [80, 85]])
result = 100 - arr
print(result)
print(arr + result)

[[ 5  3]
 [20 15]]
[[100 100]
 [100 100]]


In [17]:
# 5. 아래 2차원 배열에서 각 행에 다른 값을 곱하여 새로운 배열을 만드세요.(브로드캐스팅 이용)
a1 = np.array([[1, 2, 3], 
                [4, 5, 6]])
# 첫 번째 행은 10을 곱하고
# 두 번째 행은 100을 곱해야 합니다
a2 = np.array([[10],
               [100]])

print(a1 * a2)

[[ 10  20  30]
 [400 500 600]]


In [20]:
# 6. 아래 배열에서 각 행마다 다른 스칼라 값을 더하기 위해
# 1차원 배열을 만들어 브로드캐스팅 연산을 수행하세요.
# 첫 번째 행에 100, 두 번째 행에 200, 세 번째 행에 300을 더하세요.
a1 = np.array([[10, 20], 
               [30, 40], 
               [50, 60]])
a2 = np.array([[100],
               [200],
               [300]])
print(a1 + a2)

[[110 120]
 [230 240]
 [350 360]]


### 2-2. 통계 함수 및 집계 연산

In [ ]:
a = np.array([[1,2,3], [4,5,6]])

print("원소의 합:", np.sum(a))
print("원소의 평균:", np.mean(a))
print("표준편차:", np.std(a))
print("최대값:", np.max(a))
print("최소값:", np.min(a))
print("최대값의 인덱스:", np.argmax(a))
print("최소값의 인덱스:", np.argmin(a))

원소의 합: 21
원소의 평균: 3.5
표준편차: 1.707825127659933
최대값: 6
최소값: 1
최대값의 인덱스: 5
최소값의 인덱스: 0


In [ ]:
# 축(axis) 단위 연산
# axis = 0 -> 가장 높은 차원 기준 -> 행 기준
    # 행 기준 = 행을 따라 연산 = 행을 증가시키며 연산
# axis = 1 -> 가장 높은 차원 기준 -> 열 기준
    # 열 기준 = 열을 따라 연산 = 열을 증가시키며 연산
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print("행기준 합", np.sum(a, axis=0))
print("열기준 합", np.sum(a, axis=1))
print("행기준 평균", np.mean(a, axis=0))
print("열기준 평균", np.mean(a, axis=1))


행기준 합 [12 15 18]
열기준 합 [ 6 15 24]
행기준 평균 [4. 5. 6.]
열기준 평균 [2. 5. 8.]


In [37]:
# 누적 연산
arr = np.array([1,2,3,4])
print("누적합:", np.cumsum(arr))
print("누적곱:", np.cumprod(arr))


누적합: [ 1  3  6 10]
누적곱: [ 1  2  6 24]


In [42]:
# <실습2>
# 1. 아래 배열의 전체 합계와 평균을 각각 구하세요.
a1 = np.array([5, 10, 15, 20])

print("합:", np.sum(a1))
print("평균:", np.mean(a1))

# 2. 다음 2차원 배열에서 전체 최소값과 최대값을 구하세요.
a2 = np.array([[3, 7, 1],
               [9, 2, 8]])
print("최대값:", np.max(a2))
print("최소값:", np.min(a2))

# 3. 아래 배열에서 각 열의 합계와 각 행의 합계를 각각 구하세요.
a3 = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])
print("각 행의 합계", np.sum(a3, axis=0))
print("각 열의 합계", np.sum(a3, axis=1))

합: 50
평균: 12.5
최대값: 9
최소값: 1
각 행의 합계 [12 15 18]
각 열의 합계 [ 6 15 24]


In [45]:
# 4. 아래 배열에서 행별 평균과 열별 평균을 각각 구하세요.
a4 = np.array([[10, 20],
                [30, 40],
                [50, 60]])
print("행별 평균", np.mean(a4, axis=0))
print("열별 평균", np.mean(a4, axis=1))

# 5. 1차원 배열에서 전체 표준편차를 구하고, 각 요소가 평균으로부터 얼마나 떨어져 있는지 편차 배열을 만드세요. (값 -평균)
a5 = np.array([2, 4, 4, 4, 5, 5, 7, 9])

print("평균:", np.mean(a5))
print("표준편차:", np.std(a5))
print("편차배열:", a5 - np.mean(a5))

# 6. 아래 2차원 배열에서 행 단위 누적 합과 열 단위 누적 곱을 각각 구하세요.
a6 = np.array([[1, 2, 3],
               [4, 5, 6]])

print("행단위 누적합:\n", np.cumsum(a6, axis=0))
print("열단위 누적곱:\n", np.cumprod(a6, axis=1))


행별 평균 [30. 40.]
열별 평균 [15. 35. 55.]
평균: 5.0
표준편차: 2.0
편차배열: [-3. -1. -1. -1.  0.  0.  2.  4.]
행단위 누적합:
 [[1 2 3]
 [5 7 9]]
열단위 누적곱:
 [[  1   2   6]
 [  4  20 120]]


### 2-3. 논리 연산과 조건 연산

In [46]:
# np.where()
# 조건 기반 선택 함수

arr = np.array([10,20,30,40,50])
result = np.where(arr > 30, "High", "Low")
result

array(['Low', 'Low', 'Low', 'High', 'High'], dtype='<U4')

In [ ]:
arr = np.array([10,20,30,40,50])
# 조건만 넣을 경우 조건을 만족하는 원소의 인덱스를 반환
result = np.where(arr > 30)
print(result)
print(arr[result])                      # Fancy Indexing

(array([3, 4]),)
[40 50]


In [55]:
# 논리 연산
# and : & - 모든 조건이 True여야 True
# or : | - 조건 중에 하나라도 True면 True
# not : ~ - True -> False, Fasle -> True 로 바꿔줌

# and 연산 (&)
arr = np.array([10,20,30,40,50])
mask_and = (arr > 10) & (arr < 50)
print(mask_and)
print("&연산", arr[mask_and])

# or 연산 (|)
mask_or = (arr < 20) | (arr > 40)
print("|연산", arr[mask_or]) 

# not 연산 (~)
mask_not = ~(arr > 30)
print("~연산", arr[mask_not])

[False  True  True  True False]
&연산 [20 30 40]
|연산 [10 50]
~연산 [10 20 30]


In [71]:
# <실습3>
# 1. 1차원 배열 [5, 12, 18, 7, 30, 25]에서 10보다 크고 20보다 작은 값만 필터링하세요.
arr1 = np.array([5, 12, 18, 7, 30, 25])
mask_and = (arr1 > 10) & (arr1 < 20)
print(arr1[mask_and])

# 2. 배열 [10, 15, 20, 25, 30, 35]에서 15 이하이거나 30 이상인 값만 선택하세요.
arr2 = np.array([10, 15, 20, 25, 30, 35])
mask_or = (arr2 <= 15) | (arr2 >= 30)
print(arr2[mask_or])

# 3. 배열 [3, 8, 15, 6, 2, 20]에서 10 이상인 값을 모두 0으로 변경하세요.
arr3 = np.array([3, 8, 15, 6, 2, 20])
result3 = np.where(arr3 >= 10, 0, arr3)
print(result3)

# 4. 배열 [7, 14, 21, 28, 35]에서 20 이상인 값은 "High", 나머지는 "Low"로 표시하는 새로운 배열을 생성하세요.
arr4 = np.array([7, 14, 21, 28, 35])
result4 = np.where(arr4 >= 20, "High", "Low")
print(result4)

[12 18]
[10 15 30 35]
[3 8 0 6 2 0]
['Low' 'Low' 'High' 'High' 'High']


In [ ]:
# 5. 0~9 범위의 배열에서 짝수는 그대로 두고, 홀수는 홀수 값 ×10으로 변환한 배열을 만드세요
arr5 = np.array([0,1,2,3,4,5,6,7,8,9])
result5 = np.where(arr5 % 2 == 1, arr5*10, arr5)
print(result5)

# 6. 아래 2차원 배열 에서 20 이상 40 이하인 값만 선택하세요.
arr6 = np.array([[10, 25, 30],
                [40, 5, 15],
                [20, 35, 50]])
result6 = arr6[(arr6 >= 20) & (arr6 <= 40)]
print(result6)

# 7. 배열 [1, 2, 3, 4, 5, 6]에서 3의 배수가 아닌 값만 선택하세요
arr7 = np.array([1, 2, 3, 4, 5, 6])
# result7 = ~arr7[arr7 % 3 == 0]
result7 = arr7[arr7 % 3 != 0]
print(result7)


[ 0 10  2 30  4 50  6 70  8 90]
[25 30 40 20 35]
[1 2 4 5]


In [ ]:
# 8. 랜덤 정수(0~100) 10개 배열에서 아래와 같이 새로운 배열을 만드세요.
# 50 이상인 값은 그대로, 50 미만인 값은 50으로 변경
arr8 = np.random.randint(0, 101, 10)
# result8 = np.where(arr8 >= 50, arr8, 50)
result8 = np.where(arr8 < 50, 50, arr8)
print(result8)

# 9. 2차원 배열에서 아래와 같이 분류된 문자열 배열을 생성하세요.
# 70 이상 → "A" , 30 이상 70 미만 → "B" , 30 미만 → "C“
arr9 = np.array ([[5, 50, 95],
                  [20, 75, 10],
                  [60, 30, 85]])
result9 = np.where(arr9 >= 70, "A",np.where(arr9 >= 30, "B", "C" ))
print(result9)



[92 56 96 50 50 60 50 50 50 50]
[['C' 'B' 'A']
 ['C' 'A' 'C']
 ['B' 'B' 'A']]
