## 03. NumPy
### 3-1. 배열의 형태 변형과 차원 확장/축소

In [2]:
import numpy as np

In [ ]:
# array.ravel()
# - 다차원 배열을 1차원 배열로 펼침
# - 결과를 view로 반환(view 변경시 원본도 변경)

a = np.array([[1,2,3], [4,5,6]])
print(a)                                # [[1 2 3] /  [4 5 6]]

flat = a.ravel()
print(flat)                             # [1 2 3 4 5 6]

flat[2] = 100
print(flat)                             # [  1   2 100   4   5   6]
print(a)                                # [[  1   2 100] /  [  4   5   6]]

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[  1   2 100   4   5   6]
[[  1   2 100]
 [  4   5   6]]


In [ ]:
# array.flatten()
# - 다차원 배열을 1차원 배열로 펼침
# - 결과를 복사본으로 반환 (복사본 변경시 원본은 변경되지 않음)
a = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a)                                       # [[[1 2] / [3 4]] / [[5 6] /  [7 8]]]

flat = a.flatten()
print(flat)                                     # [1 2 3 4 5 6 7 8]

flat[4] = 0
print(flat)                                     # [1 2 3 4 0 6 7 8]
print(a)                                        # [[[1 2] / [3 4]] / [[5 6] /  [7 8]]]


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[1 2 3 4 5 6 7 8]
[1 2 3 4 0 6 7 8]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# np.expand_dims(a, axis)
# 지정한 위치에 차원 추가 (차원 확장)
# 추가되는 차원은 1
a = np.array([[1,2,3],[4,5,6]])
print("원본:", a.shape)             # 원본: (2, 3)

# axis = 0
a0 = np.expand_dims(a, axis=0)
print("a0", a0.shape)               # a0 (1, 2, 3)
print("a0", a0)                     # a0 [[[1 2 3] / [4 5 6]]]

# axis =1
a1 = np.expand_dims(a, axis=1)
print("a1", a1.shape)               # a1 (2, 1, 3)
print("a1", a1)                     # a1 [[[1 2 3]] / [[4 5 6]]]

# axis = 2
a2 = np.expand_dims(a, axis=2)     
print("a2", a2.shape)               # a2 (2, 3, 1)
print("a2", a2)                     # a2 [[[1] / [2] / [3]] // [[4] / [5] /  [6]]]


원본: (2, 3)
a0 (1, 2, 3)
a0 [[[1 2 3]
  [4 5 6]]]
a1 (2, 1, 3)
a1 [[[1 2 3]]

 [[4 5 6]]]
a2 (2, 3, 1)
a2 [[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]


In [ ]:
# np.squeeze(a, axis)
# - 배열에서 크기가 1인 차원을 제거해주는 함수 (차원 축소)
a = np.array([[[[1],[2],[3]]], [[[1],[2],[3]]]])
print(a.shape)                      # (2, 1, 3, 1)

s = np.squeeze(a)
print(s)                            # [[1 2 3] / [1 2 3]]
print(s.shape)                      # (2, 3)

(2, 1, 3, 1)
[[1 2 3]
 [1 2 3]]
(2, 3)


In [ ]:
# axis 지정하는 경우
a2 = np.zeros((1,4,1,2))
print(a2.shape)                     # (1, 4, 1, 2)

s1 = np.squeeze(a2, axis = 0)
print(s1.shape)                     # (4, 1, 2)

s2 = np.squeeze(a2, axis = 2)
print(s2.shape)                     # (1, 4, 2)


# 차원의 크기가 1이 아닌 차원은 제거할 수 X
s3 = np.squeeze(a2, axis=1)         # ValueError

(1, 4, 1, 2)
(4, 1, 2)
(1, 4, 2)


ValueError: cannot select an axis to squeeze out which has size not equal to one

In [ ]:
# np.unique()
# - 배열에서 중복된 요소를 제거
a = np.array([1,1,1,5,5,2,2,2,2,4,4,4,3,3,3])
u1 = np.unique(a) # 고유값의 오름차순 배열 반환
print(u1)                                       # [1 2 3 4 5]

u2, idx, inv, cnt = np.unique(a, return_index=True, return_inverse=True, return_counts=True)
print("인덱스:", idx)                           # 인덱스: [ 0  5 12  9  3]
print("원본의 고유값 인덱스:", inv)             # 원본의 고유값 인덱스: [0 0 0 4 4 1 1 1 1 3 3 3 2 2 2]
print("값의 등장 횟수:", cnt)                   # 값의 등장 횟수: [3 4 3 3 2]



[1 2 3 4 5]
인덱스: [ 0  5 12  9  3]
원본의 고유값 인덱스: [0 0 0 4 4 1 1 1 1 3 3 3 2 2 2]
값의 등장 횟수: [3 4 3 3 2]


In [ ]:
# <실습1>
# 1. 아래의 배열을 사용해서
arr = np.array([[10, 20], [30, 40], [50, 60]])
# 1) ravel과 flatten을 각각 사용해 1차원 배열로 변환하고,
flat1 = arr.ravel()
print(flat1)                            # [10 20 30 40 50 60]

flat2 = arr.flatten()
print(flat2)                            # [10 20 30 40 50 60]

# 2) arr의 첫 번째 원소(arr[0,0])를 999로 바꾼 뒤 ravel 결과와 flatten 결과에 어떤 변화가 있는지 확인하세요.
arr[0,0] = 999
print(flat1)                            # [999  20  30  40  50  60]
print(flat2)                            # [10 20 30 40 50 60]


[10 20 30 40 50 60]
[10 20 30 40 50 60]
[999  20  30  40  50  60]
[10 20 30 40 50 60]


In [ ]:
# 2. 크기가 32x32인 이미지 데이터를 가정하고, 이 배열에 대해 expand_dims를 사용하여 shape (1, 32, 32)로 바꾸는 코드를 작성하세요.
img= np.random.rand(32, 32)
img1 = np.expand_dims(img, axis=0)
print(img)                  
print(img1.shape)                       # (1, 32, 32)

[[0.80987598 0.0020947  0.6520447  ... 0.59621249 0.74312251 0.86442736]
 [0.50507662 0.95452171 0.74998294 ... 0.85114743 0.77676529 0.84708677]
 [0.21481874 0.08495728 0.2887748  ... 0.75475553 0.69142819 0.1384524 ]
 ...
 [0.54684402 0.62120009 0.66787636 ... 0.87300256 0.25162257 0.6664204 ]
 [0.75222249 0.25640919 0.98349194 ... 0.63728423 0.74837749 0.14222578]
 [0.75039205 0.54913399 0.86723695 ... 0.42047971 0.34540019 0.99862679]]
(1, 32, 32)


In [ ]:
# 3. 아래 배열에서 불필요한 1차원을 모두 제거하여 shape이 (28, 28)이 되도록 만드세요.
img= np.random.randint (0, 255, (1, 28, 28, 1))
s = np.squeeze(img)
print(s)
print(s.shape)                          # (28, 28)

(28, 28)


In [ ]:
# 4. 아래 2차원 배열을 1) 1차원 배열로 만든 후 2) 중복값을 제거한 뒤 shape (1, n)으로 재구성하세요.
arr = np.array([[3, 1, 2, 2],
                [1, 2, 3, 1],
                [2, 2, 1, 4]])

flat = arr.flatten()
print(flat)                             # [3 1 2 2 1 2 3 1 2 2 1 4]
u1 = np.unique(flat)
print(u1)                               # [1 2 3 4]
u2 = u1.reshape(1, -1)  # -1을 입력할시 자동으로 계산해줌
print(u2)                               # [[1 2 3 4]]
print(u2.shape)                         # (1, 4)


[3 1 2 2 1 2 3 1 2 2 1 4]
[1 2 3 4]
[[1 2 3 4]]
(1, 4)


In [ ]:
# 5. 다음 배열을 shape (10,)로 만든 뒤 고유값배열을 구하세요.
arr = np.array([[[1], [3], [2], [1], [3], [2], [3], [1], [2], [3]]]) # shape(1, 10, 1)  # 3차원

s = np.squeeze(arr)
print(s)                                # [1 3 2 1 3 2 3 1 2 3]

u = np.unique(s)
print(u)                                # [1 2 3]


[1 3 2 1 3 2 3 1 2 3]
[1 2 3]


In [ ]:
# 6. 다음 배열을 1차원 배열로 만든 후 고유값만 추출해서 shape (고유값 개수, 1)인 2차원 배열로 변환하세요.
arr = np.array([ [[ 0, 1, 2, 3], [1, 2, 3, 4], [2, 3, 4, 5]],
                [[3, 4, 5, 6], [4, 5, 6, 7], [5, 6, 7, 8]] ]) # shape (2, 3, 4)
flat = arr.flatten()
print(flat)                             # [0 1 2 3 1 2 3 4 2 3 4 5 3 4 5 6 4 5 6 7 5 6 7 8]

u = np.unique(flat)
print(u)                                # [0 1 2 3 4 5 6 7 8]
print(u.shape)                          # (9,)

r = np.expand_dims(u, axis=1)
print(r)                                # [[0]/[1]/[2]/[3]/[4]/[5]/[6]/[7]/[8]]
print(r.shape)                          # (9, 1)


[0 1 2 3 1 2 3 4 2 3 4 5 3 4 5 6 4 5 6 7 5 6 7 8]
[0 1 2 3 4 5 6 7 8]
(9,)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
(9, 1)


### 3-2. 배열의 결합과 분리

In [ ]:
# np.concatenate()
# 배열 시퀀스를 결합
# 기존 구조 안에서 결합
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])

result1 = np.concatenate((a,b), axis = 0)   # 행
print(result1)                                  # [[1 2]/[3 4]/[5 6]]
print(result1.shape)                            # (3, 2)

# 결합이 불가 -> 결합하는 axis를 제외한 나머지 차원이 같아야 함
# result2 = np.concatenate((a,b), axis = 1)    # ValueError

c = np.array([[7],[8],[9]])
result3 = np.concatenate((result1, c), axis = 1)
print(result3)                                  # [[1 2 7]/[3 4 8]/[5 6 9]]
print(result3.shape)                            # (3, 3)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)
[[1 2 7]
 [3 4 8]
 [5 6 9]]
(3, 3)


In [ ]:
# np.stack()
# 새로운 차원을 추가하면서 결합
a = np.array([1,2,3])
b = np.array([4,5,6])

# axis = 0
s1 = np.stack((a,b), axis = 0)
print(s1)                                   # [[1 2 3]/[4 5 6]]
print(s1.shape)                             # (2, 3)

# axis = 1
s2 = np.stack((a,b), axis =1)
print(s2)                                   # [[1 4]/[2 5]/[3 6]]
print(s2.shape)                             # (3, 2)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 4]
 [2 5]
 [3 6]]
(3, 2)


In [ ]:
# hstack()
# - 열 방향 (가로)로 결합
a = np.array([1,2,3])
b = np.array([4,5,6])

h = np.hstack((a,b))
print(h)                        # [1 2 3 4 5 6]

# vstack()
# - 행 방향 (세로)로 결합
v = np.vstack((a,b))
print(v)                        # [[1 2 3]/[4 5 6]]


[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [ ]:
# np.split()
# 배열을 여러개의 하위 배열로 분할
a = np.arange(9)
s = np.split(a, 3)
print(a)                        # [0 1 2 3 4 5 6 7 8]
print(s)                        # [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
print(s[0])                     # [0 1 2]
print(s[1])                     # [3 4 5]
print(s[2])                     # [6 7 8]

# 같은 크기로만 나눌 수 있다
# s2 = np.split(a, 4)     # ValueError

# np.split(배열, [a,b]) → 배열을 a, b 위치에서 나누어서 3개 부분으로 분할


[0 1 2 3 4 5 6 7 8]
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
[0 1 2]
[3 4 5]
[6 7 8]


In [ ]:
a = np.arange(16).reshape(4,4)
print(a)                          # [[ 0  1  2  3]/[ 4  5  6  7]/[ 8  9 10 11]/[12 13 14 15]]

s1 = np.split(a, [1, 3])
print(s1)                         # [array([[0, 1, 2, 3]]), array([[ 4,  5,  6,  7],/[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]
for part in s1:
    print(part)                   # [[0 1 2 3]] / [[ 4  5  6  7] /  [ 8  9 10 11]] / [[12 13 14 15]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[0, 1, 2, 3]]), array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]
[[0 1 2 3]]
[[ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]]


In [107]:
# <실습2>
# 1. 다음 두 배열을 행 방향으로 이어붙이세요.
a1 = np.array([[1, 2], [3, 4]])
b1 = np.array([[5, 6]])

result = np.concatenate((a1,b1), axis = 0)
print("1번:\n",result)

# 2. 아래 배열을 3개로 같은 크기로 분할하세요.
a2 = np.arange(12)
s2 = np.split(a2, 3)
print("2번\n", s2)

# 3. 다음 배열들을 새로운 축에 쌓아 shape이 (3, 2)인 배열을 만드세요.
a3 = np.array([1, 2])
b3 = np.array([3, 4])
c3 = np.array([5, 6])

s3 = np.stack((a3,b3,c3), axis = 0)
print("3번\n", s3, s3.shape)

1번:
 [[1 2]
 [3 4]
 [5 6]]
2번
 [array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]
3번
 [[1 2]
 [3 4]
 [5 6]] (3, 2)


In [ ]:
# 4. shape가 (2, 3)인 아래 두 배열을 shape (2, 2, 3)인 3차원 배열을 만드세요.
a4 = np.array([[1, 2, 3], [4, 5, 6]])
b4 = np.array([[7, 8, 9], [10, 11, 12]])

s4 = np.stack((a4,b4), axis = 0)
print("4번\n",s4)
print(s4.shape)

# 5. 아래의 1차원 배열을 2:3:3 비율(총 3개)로 분할하세요.
a5 = np.arange(8)
print("5번\n",np.split(a5,[2,5]))         

# 6. 아래 두 배열을 axis=0, axis=1로 각각 stack하여 두 경우의 결과 shape을 모두 구하세요
a6 = np.ones((2, 3))
b6 = np.zeros((2, 3))

s6_1 = np.stack((a6,b6), axis = 0)
s6_2 = np.stack((a6,b6), axis = 1)
print("6번\n",s6_1)
print(s6_1.shape)
print(s6_2)
print(s6_2.shape)

4번
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
5번
 [array([0, 1]), array([2, 3, 4]), array([5, 6, 7])]
6번
 [[[1. 1. 1.]
  [1. 1. 1.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
(2, 2, 3)
[[[1. 1. 1.]
  [0. 0. 0.]]

 [[1. 1. 1.]
  [0. 0. 0.]]]
(2, 2, 3)


### 3-3. 배열의 정렬

In [ ]:
# np.sort(array)
# 정렬된 복사본 반환
# array.sort()
# 원본 배열을 정렬

# 1차원 배열
a = np.array([3,1,4,2])

# 정렬한 배열을 반환
s = np.sort(a)
print(s)
print(a)

# 원본을 정렬
a.sort()
print(a)

# 내림차순 : sort한 후 배열을 뒤집어야 함
print(a[::-1])



[1 2 3 4]
[3 1 4 2]
[1 2 3 4]
[4 3 2 1]


In [ ]:
# 2차원 배열 정렬
a = [[6,5,4], [3,1,2]]
s1 = np.sort(a, axis = 0) # 행이 바뀜
print(s1)
s2 = np.sort(a, axis = 1) # 열끼리 정렬
print(s2)

[[3 1 2]
 [6 5 4]]
[[4 5 6]
 [1 2 3]]


In [115]:
# np.argsort()
# - 정렬 인덱스를 반환

a = np.array([3,5,1,2,4])
idx = np.argsort(a)
print(idx)
print(a[idx])

[2 3 0 4 1]
[1 2 3 4 5]


In [130]:
# 1.아래의 1차원 배열을 오름차순과 내림차순으로 각각 정렬하는 코드를 작성하세요.
a1 = np.array([7, 2, 9, 4, 5])

print("오름차순:", np.sort(a1))
print("내림차순:", np.sort(a1)[::-1])

# 2. 아래의 2차원 배열에서 각 행(row) 별로 오름차순 정렬된 배열을 구하세요.
a2 = np.array([[9, 2, 5],
               [3, 8, 1]])

print("2번\n",np.sort(a2, axis=1))


오름차순: [2 4 5 7 9]
내림차순: [9 7 5 4 2]
2번
 [[2 5 9]
 [1 3 8]]


In [132]:
# 3. 아래의 1차원 배열에서 정렬 결과(오름차순)가 되는 인덱스 배열을 구하고, 그 인덱스를 이용해 원본 배열을 직접 재정렬하는 코드를 작성하세요.
a3 = np.array([10, 3, 7, 1, 9])
idx = np.argsort(a3)
print("3번\n",idx)
print(a3[idx])


# 4. 아래 2차원 배열을 열(column) 기준(axis=0)으로 오름차순 정렬된 배열을 구하세요.
a4 = np.array([[4, 7, 2],
               [9, 1, 5],
               [6, 8, 3]])
print("4번\n", np.sort(a4, axis=0))

3번
 [3 1 2 4 0]
[ 1  3  7  9 10]
4번
 [[4 1 2]
 [6 7 3]
 [9 8 5]]
