## 03. 텐서의 조작

In [1]:
import torch

### 3-1. 인덱싱, 슬라이싱
- numpy와 동일한 방식으로 인덱싱, 슬라이싱 가능

In [3]:
x = torch.tensor([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print(x[1,1])  # 5
print(x[2,0])  # 7
print(x[0, :]) # 0행 전체 1,2,3
print(x[:, 2]) # 2열 전체 3,6,9
print(x[[0,1,2], [0,1,2]]) # fancy 인덱싱 1,5,9
print(x[x > 5]) # boolean 인덱싱 6,7,8,9

tensor(5)
tensor(7)
tensor([1, 2, 3])
tensor([3, 6, 9])
tensor([1, 5, 9])
tensor([6, 7, 8, 9])


In [5]:
x = torch.tensor([10,20,30,40,50])

x[0] = 100
print(x)

# 슬라이싱으로 값을 변경할 시 tensor로 값을 할당
x[1:4] = torch.tensor([200,300,400])
print(x)

tensor([100,  20,  30,  40,  50])
tensor([100, 200, 300, 400,  50])


### 3-2. 텐서의 크기, 모양 변경
- torch.view()

In [7]:
x = torch.randn(4,5)    
print(x)                # 2차원

y = x.view(20)
print(y)                # 1차원으로 바뀜

z = y.view(5,-1)        # -1 넣게 되면 자동으로 계산
print(z)

n = z.view(2, 2, 5)     # 3차원
print(n)

tensor([[-1.4593e+00,  4.5164e-01,  9.6214e-01, -1.4170e-04, -1.7275e+00],
        [-8.0893e-01, -1.0052e+00,  1.2167e+00,  1.0036e+00,  2.6348e+00],
        [-6.6281e-02,  1.8174e-01, -1.8754e-01,  6.8849e-01,  1.5541e+00],
        [ 9.8371e-01,  2.5057e-01, -4.2412e-01,  2.5569e-01, -1.4897e-01]])
tensor([-1.4593e+00,  4.5164e-01,  9.6214e-01, -1.4170e-04, -1.7275e+00,
        -8.0893e-01, -1.0052e+00,  1.2167e+00,  1.0036e+00,  2.6348e+00,
        -6.6281e-02,  1.8174e-01, -1.8754e-01,  6.8849e-01,  1.5541e+00,
         9.8371e-01,  2.5057e-01, -4.2412e-01,  2.5569e-01, -1.4897e-01])
tensor([[-1.4593e+00,  4.5164e-01,  9.6214e-01, -1.4170e-04],
        [-1.7275e+00, -8.0893e-01, -1.0052e+00,  1.2167e+00],
        [ 1.0036e+00,  2.6348e+00, -6.6281e-02,  1.8174e-01],
        [-1.8754e-01,  6.8849e-01,  1.5541e+00,  9.8371e-01],
        [ 2.5057e-01, -4.2412e-01,  2.5569e-01, -1.4897e-01]])
tensor([[[-1.4593e+00,  4.5164e-01,  9.6214e-01, -1.4170e-04, -1.7275e+00],
         [-8.0893e-

### 3-3. 텐서의 숫자값 얻기
- tensor.item() : 스칼라 값 하나만 존재해야 사용 가능

In [9]:
x = torch.rand(2)
print(x)
print(x[0])

print(x[0].item())

tensor([0.1315, 0.9065])
tensor(0.1315)
0.13151389360427856


### 3-4. 차원 축소 및 증가
#### 차원 축소(제거)
- torch.squeeze : 크기가 1인 차원을 제거함

In [13]:
t = torch.rand(3, 1, 3)
print(t)
print(t.shape)

ts = torch.squeeze(t)
print(ts)
print(ts.shape)

tensor([[[0.1743, 0.5327, 0.6848]],

        [[0.2369, 0.6873, 0.5194]],

        [[0.9478, 0.0179, 0.3397]]])
torch.Size([3, 1, 3])
tensor([[0.1743, 0.5327, 0.6848],
        [0.2369, 0.6873, 0.5194],
        [0.9478, 0.0179, 0.3397]])
torch.Size([3, 3])


#### 차원 증가(생성)
- torch.unsqueeze() : 차원 설정에 따라 차원을 증가시킴
    - 차원은 하나의 차원이 추가되는 인덱스

In [18]:
t = torch.rand(3, 3, 3)
print(t.shape)

# 0 가장 상위 차원 -> 3 가장 하위 차원
ts1 = torch.unsqueeze(t, dim=0)
print(ts1.shape)

ts2 = torch.unsqueeze(t, dim=1)
print(ts2.shape)

ts3 = torch.unsqueeze(t, dim=2)
print(ts3.shape)

ts4 = torch.unsqueeze(t, dim=3)
print(ts4.shape)


torch.Size([3, 3, 3])
torch.Size([1, 3, 3, 3])
torch.Size([3, 1, 3, 3])
torch.Size([3, 3, 1, 3])
torch.Size([3, 3, 3, 1])


### 3-5. 텐서간 결합
- torch.stack() : 동일한 형식의 텐서를 새롭게 그룹화함 -> 새로운 차원 생성됨

In [20]:
x = torch.tensor([1, 4])
y = torch.tensor([2, 5])
z = torch.tensor([3, 6])
result = torch.stack([x, y, z])
print(result)

a = torch.tensor([[1,2], [3,4]])
b = torch.tensor([[5,6], [7,8]])
result2 = torch.stack([a,b])
print(result2)

tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


- torch.cat() : 데이터를 하나의 텐서로 병합 -> 새로운 차원 생성 X

In [21]:
a = torch.tensor([[1,2], [3,4]])
b = torch.tensor([[7,8], [9,10]])

result = torch.cat([a,b], dim=1)
print(result)

tensor([[ 1,  2,  7,  8],
        [ 3,  4,  9, 10]])


### 3-6. 텐서 나누기
- torch.chunk() : 텐서를 지정한 개수에 따라 나눔
    - 나누어 떨어지지 않는 경우 -> 마지막 조각의 크기가 달라짐
- torch.split() : 지정한 사이즈에 따라 나눔
    - 나누어 떨어지지 않은 경우 -> 마지막 조각의 크기를 명시할 수 있음

In [ ]:
t = torch.rand(3,7)
print(t)

t1, t2, t3 = torch.chunk(t, 3, dim=1)
print(t1)
print(t2)
print(t3)

tensor([[0.8688, 0.6572, 0.9220, 0.9844, 0.0681, 0.0022, 0.1269],
        [0.3102, 0.9454, 0.6231, 0.8697, 0.3092, 0.0429, 0.8906],
        [0.9229, 0.4719, 0.2568, 0.4809, 0.3034, 0.3365, 0.1534]])
tensor([[0.8688, 0.6572, 0.9220],
        [0.3102, 0.9454, 0.6231],
        [0.9229, 0.4719, 0.2568]])
tensor([[0.9844, 0.0681, 0.0022],
        [0.8697, 0.3092, 0.0429],
        [0.4809, 0.3034, 0.3365]])
tensor([[0.1269],
        [0.8906],
        [0.1534]])


In [ ]:
t = torch.rand(3,7)
print(t)

# 쪼갤 열의 개수 지정
t1, t2, t3 = torch.split(t, [2, 3, 2], dim=1)
print(t1)
print(t2)
print(t3)

tensor([[1.6556e-01, 9.7965e-01, 2.9190e-03, 8.1277e-01, 8.3551e-01, 2.2791e-01,
         6.6887e-01],
        [1.0132e-01, 2.9599e-01, 3.2002e-01, 1.3337e-01, 5.2180e-01, 1.0535e-02,
         5.6257e-01],
        [7.1922e-01, 5.9929e-01, 3.3863e-01, 3.5003e-01, 9.7377e-01, 7.8475e-04,
         7.4715e-02]])
tensor([[0.1656, 0.9796],
        [0.1013, 0.2960],
        [0.7192, 0.5993]])
tensor([[0.0029, 0.8128, 0.8355],
        [0.3200, 0.1334, 0.5218],
        [0.3386, 0.3500, 0.9738]])
tensor([[0.2279, 0.6689],
        [0.0105, 0.5626],
        [0.0008, 0.0747]])
