## PyTorch Quiz 1 : Tensor 초기화

In [1]:
import torch

### 1. 빈 Tensor 생성하기
다음 조건에 맞는 Tensor를 생성하세요.
- 3x4 크기의 Tensor
- 값이 초기화되지 않은 상태

In [2]:
x = torch.empty(3, 4)
print(x)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


### 2. 0으로 채워진 Tensor 생성하기
다음과 같은 Tensor를 생성하세요.
- 2x5x3 크기의 Tensor
- 데이터 타입은 float64

In [14]:
x = torch.zeros(2, 5, 3, dtype=torch.float64)
print(x)

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]], dtype=torch.float64)


### 3. 1로 채워진 Tensor 생성하기
다음 조건에 맞는 Tensor를 생성하세요.
- 4x4 크기의 Tensor
- 데이터 타입은 int

In [9]:
x = torch.ones(4,4, dtype=torch.int)
print(x)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)


### 4. 랜덤 값으로 채워진 Tensor 생성하기
다음 조건에 맞는 Tensor를 생성하세요.
- 3x3 크기의 Tensor
- 모든 값이 0과 1 사이의 랜덤 값

In [10]:
x = torch.rand(3,3)
print(x)

tensor([[0.1235, 0.0584, 0.1470],
        [0.3836, 0.0280, 0.6269],
        [0.3979, 0.2580, 0.6251]])


### 5. 다차원 Tensor 생성하기
다음과 같은 다차원 Tensor를 생성하세요.
- 값이 다음과 같은 2x3의 2D 배열
    ```
    [[1, 2, 3],
     [4, 5, 6]]
    ```

In [ ]:

x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

print(x)

tensor([[1, 2, 3],
        [4, 5, 6]])


### 6. Tensor의 값을 변경하기
1. 표준정규분포의 값을 랜덤으로 갖는 2x2 Tensor를 생성하세요.
2. 생성된 Tensor의 속성을 물려받은 원소가 0인 새로운 텐서를 만들어보세요. 

In [15]:
x = torch.randn(2, 2, dtype=torch.float64)
print(x)
y = x.new_zeros(2, 2)
print(y)


tensor([[ 0.0222,  0.8738],
        [ 3.6577, -1.7557]], dtype=torch.float64)
tensor([[0., 0.],
        [0., 0.]], dtype=torch.float64)
