## PyTorch Quiz 2 : 연산

In [1]:
import torch

### 1. 덧셈과 뺄셈 연습
1. [2, 4, 6]으로 초기화된 1D Tensor를 생성하세요.
2. 각 요소에 5를 더한 Tensor를 출력하세요.
3. 각 요소에서 3을 뺀 Tensor를 출력하세요.


In [ ]:
x = torch.tensor([2,4,6])
print(x)
x = x + 5 # add
print(x)
x = x - 3
print(x)

tensor([2, 4, 6])
tensor([ 7,  9, 11])
tensor([4, 6, 8])


### 2. Tensor 간의 연산
1. 3x3 크기의 Tensor 2개를 생성하세요.
2. 두 Tensor를 각각 더하고(+), 빼고(-), 곱하고(*), 나누세요(/).

In [6]:
x = torch.rand(3,3)
y = torch.rand(3,3)

print("x", x)
print("y", y)

# 더하기
print("더하기", x + y)

# 빼기
print("빼기", x - y) 

# 곱하기
print("곱하기", x * y)

# 나누기
print("나누기", x / y)

x tensor([[0.1144, 0.0466, 0.6116],
        [0.6140, 0.9285, 0.9107],
        [0.6891, 0.9824, 0.4934]])
y tensor([[0.0566, 0.0700, 0.5681],
        [0.1135, 0.3420, 0.2927],
        [0.3318, 0.8245, 0.7928]])
더하기 tensor([[0.1710, 0.1166, 1.1798],
        [0.7275, 1.2705, 1.2034],
        [1.0209, 1.8069, 1.2862]])
빼기 tensor([[ 0.0578, -0.0234,  0.0435],
        [ 0.5005,  0.5865,  0.6180],
        [ 0.3573,  0.1579, -0.2994]])
곱하기 tensor([[0.0065, 0.0033, 0.3475],
        [0.0697, 0.3176, 0.2666],
        [0.2287, 0.8100, 0.3911]])
나누기 tensor([[2.0220, 0.6653, 1.0766],
        [5.4102, 2.7147, 3.1113],
        [2.0767, 1.1915, 0.6223]])


### 3. 행렬의 내적 연산
1. 2×3 크기의 Tensor A를 다음 값으로 생성하세요:
  - `[[1,2,3], [4,5,6]]`
2. 3×2 크기의 Tensor B를 다음 값으로 생성하세요:
  - `[[7,8],[9,10],[11,12]]`
3. 두 Tensor의 행렬 내적(행렬 곱) A×B를 계산하여 출력하세요.

In [ ]:
A = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

B = torch.tensor([[7, 8],
                  [9, 10],
                  [11, 12]])

print(torch.matmul(A, B))

tensor([[ 58,  64],
        [139, 154]])


### 4. 행렬 연산과 값 제한
1. 이전 문제에서 계산된 행렬 R(결과 행렬 A×B)를 사용하세요
2. 행렬 R의 각 요소에 10을 더하세요.
3. R의 각 요소를 100보다 큰 값은 100으로, 나머지는 그대로 유지하도록 제한하세요.

In [9]:
R = torch.tensor([[ 58,  64],
                  [139, 154]])
R = R + 10
print(R)

R = torch.clamp(R, max=100)
print(R)

tensor([[ 68,  74],
        [149, 164]])
tensor([[ 68,  74],
        [100, 100]])


### 5. 행렬의 열별 합계 계산
1. 5×5 크기의 Tensor M을 다음 값으로 생성하세요
    ```
    [[1, 2, 3, 4, 5],
     [6, 7, 8, 9, 10],
     [11, 12, 13, 14, 15],
     [16, 17, 18, 19, 20],
     [21, 22, 23, 24, 25]]
    ```

2. 행렬 M의 각 열의 합계를 계산하세요.

In [11]:
M = torch.tensor([[ 1,  2,  3,  4,  5],
                  [ 6,  7,  8,  9, 10],
                  [11, 12, 13, 14, 15],
                  [16, 17, 18, 19, 20],
                  [21, 22, 23, 24, 25]])

print(M)
print("열의 합", torch.sum(M, dim=0))


tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]])
열의 합 tensor([55, 60, 65, 70, 75])
